FROM jenkins/jenkins:lts-jdk21


USER root


# 기본 패키지
RUN apt-get update \
    && apt-get install -y \
        ca-certificates \
        curl \
        git \
        gnupg \
    && rm -rf /var/lib/apt/lists/*


# ==========================================
# Node.js 22
# ==========================================

RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs


# ==========================================
# Docker Repository
# ==========================================

RUN install -m 0755 -d /etc/apt/keyrings


RUN curl -fsSL https://download.docker.com/linux/debian/gpg \
    -o /etc/apt/keyrings/docker.asc


RUN chmod a+r /etc/apt/keyrings/docker.asc


RUN echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" \
    > /etc/apt/sources.list.d/docker.list


RUN apt-get update \
    && apt-get install -y \
        docker-ce-cli \
        docker-compose-plugin \
    && rm -rf /var/lib/apt/lists/*


USER jenkins